sample_str = input()
sample_str = sample_str.replace(",", "")
sample_str = sample_str.replace(".", "")
sample_str = sample_str.replace("!", "")
sample_str = sample_str.replace("?", "")
print(sample_str.lower())
